apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-2
spec:
  containers:
  - name: demo-container
    image: nginx
    env:
    - name: MYAGE
      valueFrom:   
        configMapKeyRef:   
          name: configmap-2
          key:  age
    - name: MYNAME
      valueFrom:   
        configMapKeyRef:   
          name: configmap-2
          key:  name
